/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  access_token: string | null;
  access_token_expires_at: Timestamp | null;
  account_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: Timestamp | null;
  scope: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PlatformDomainEvent {
  actor_person_id: string | null;
  causation_id: string | null;
  correlation_id: string;
  event_type: string;
  id: string;
  kind: Generated<"domain" | "admin" | "security">;
  occurred_at: Generated<Timestamp>;
  on_behalf_of: string | null;
  payload: Generated<Json>;
  published_at: Timestamp | null;
  recorded_at: Generated<Timestamp>;
  schema_version: number;
  stream_id: string;
  stream_type: string;
}

export interface PlatformEventConsumption {
  consumed_at: Generated<Timestamp>;
  consumer: string;
  event_id: string;
}

export interface PlatformPerson {
  access_valid_until: Timestamp | null;
  agency_worker_reference: string | null;
  contact_email: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  date_of_birth: string | null;
  deleted_at: Timestamp | null;
  display_name: string;
  family_name: string | null;
  given_name: string | null;
  id: string;
  profile_status: Generated<"draft_shell" | "information_requested" | "information_submitted" | "pending_review" | "incomplete_rejected" | "approved_not_active" | "active" | "active_with_restrictions" | "inactive" | "leaver" | "reactivated">;
  relationship_type: "employee" | "agency" | "subcontractor" | "self_employed" | "external_org_employee" | "candidate";
  status: Generated<"active" | "inactive" | "superseded">;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface PlatformPersonFlag {
  created_at: Generated<Timestamp>;
  end_reason: string | null;
  ended_at: Timestamp | null;
  ended_by: string | null;
  flag_type: "do_not_rehire" | "safeguarding" | "safety" | "other";
  id: string;
  person_id: string;
  raised_at: Timestamp;
  raised_by: string;
  reason: string;
  source_flag_id: string | null;
  source_merge_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PlatformPersonMerge {
  created_at: Generated<Timestamp>;
  id: string;
  merged_at: Timestamp;
  merged_by: string;
  moved_user_ids: Json;
  reason: string;
  reversal_reason: string | null;
  reversed_at: Timestamp | null;
  reversed_by: string | null;
  superseded_person_id: string;
  surviving_person_id: string;
  updated_at: Generated<Timestamp>;
}

export interface RateLimit {
  count: number;
  id: string;
  key: string;
  last_request: Int8;
}

export interface Session {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  impersonated_by: string | null;
  ip_address: string | null;
  token: string;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
  user_id: string;
}

export interface User {
  ban_expires: Timestamp | null;
  ban_reason: string | null;
  banned: Generated<boolean>;
  created_at: Generated<Timestamp>;
  email: string;
  email_verified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  person_id: string | null;
  role: Generated<"admin" | "agent">;
  updated_at: Generated<Timestamp>;
}

export interface Verification {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  identifier: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  "platform.domain_event": PlatformDomainEvent;
  "platform.event_consumption": PlatformEventConsumption;
  "platform.person": PlatformPerson;
  "platform.person_flag": PlatformPersonFlag;
  "platform.person_merge": PlatformPersonMerge;
  rate_limit: RateLimit;
  session: Session;
  user: User;
  verification: Verification;
}
