/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  access_token: string | null;
  access_token_expires_at: Timestamp | null;
  account_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: Timestamp | null;
  scope: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PlatformApprovalAssignee {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  delegation_id: string | null;
  id: string;
  notified_at: Timestamp | null;
  person_id: string;
  request_id: string;
  source: "policy_role" | "designated" | "delegation";
  source_role_id: string | null;
}

export interface PlatformApprovalDecision {
  actor_person_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  decided_at: Timestamp;
  decision: "approved" | "rejected";
  delegation_id: string | null;
  id: string;
  reason: string | null;
  request_id: string;
  warnings_acknowledged: Generated<Json>;
}

export interface PlatformApprovalDelegation {
  created_at: Generated<Timestamp>;
  created_by: string;
  delegate_person_id: string;
  delegator_person_id: string;
  deleted_at: Timestamp | null;
  id: string;
  reason: string | null;
  revoked_at: Timestamp | null;
  subject_type: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  valid_from: Timestamp;
  valid_to: Timestamp;
}

export interface PlatformApprovalRequest {
  /**
   * PII-minimal facts for warning providers and threshold rules: ids, dates, amounts (ADR-0019). Never names or free text — a provider needing detail reads it live under its own RBAC.
   */
  context: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  decided_at: Timestamp | null;
  deleted_at: Timestamp | null;
  id: string;
  policy_key: string;
  policy_version: number | null;
  requested_by: string | null;
  status: Generated<"pending" | "approved" | "rejected" | "cancelled">;
  subject_id: string;
  subject_type: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  workflow_action: string | null;
  workflow_instance_id: string | null;
}

export interface PlatformConfigEntry {
  created_at: Generated<Timestamp>;
  created_by: string;
  id: string;
  key: string;
  namespace: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  valid_from: Timestamp;
  valid_to: Timestamp | null;
  /**
   * Validated against the key's registered Zod schema on write AND on read (@repo/trpc config registry). A value failing its schema on read is registry drift and raises rather than returning a guess.
   */
  value: Json;
  version: number;
}

export interface PlatformDocument {
  body_html: string | null;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  capture_data: Json | null;
  capture_schema_key: string | null;
  category_id: string;
  category_kind: Generated<"document_category">;
  completed_at: Timestamp | null;
  completed_by: string | null;
  /**
   * sha256:<hex> of the rendered PDF bytes. Settable once (NULL -> value) and never rewritable, enforced by document_guard: a hash that could change would make every signature bound to it deniable.
   */
  content_hash: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  evidence_sp_item_id: string | null;
  filed_at: Timestamp | null;
  filing_attempts: Generated<number>;
  filing_error: string | null;
  filing_state: Generated<"none" | "pending" | "filed" | "failed">;
  id: string;
  issue_group_id: string | null;
  issue_mode: "read_only" | "read_and_sign" | "no_action" | "receipt_only" | "read_and_understood" | "qa_response" | "text_response" | "file_upload";
  issued_at: Timestamp | null;
  issued_by: string | null;
  merge_data: Json | null;
  /**
   * Transient render staging only: the rendered PDF between the render step and a successful upload, NULLed once filed. SharePoint is the byte store of record. Registered with plan 16's erasure inventory — transient or not, it holds a rendered document about a person.
   */
  pending_content: Buffer | null;
  response_sp_item_id: string | null;
  sequence_no: number | null;
  signed_at: Timestamp | null;
  sp_drive_id: string | null;
  sp_item_id: string | null;
  sp_site_id: string | null;
  sp_web_url: string | null;
  status: Generated<"draft" | "issued" | "viewed" | "signed" | "completed" | "cancelled">;
  subject_person_id: string;
  subject_stream_id: string | null;
  subject_stream_type: string | null;
  template_id: string | null;
  text_response: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  viewed_at: Timestamp | null;
}

export interface PlatformDomainEvent {
  actor_person_id: string | null;
  causation_id: string | null;
  correlation_id: string;
  event_type: string;
  id: string;
  kind: Generated<"domain" | "admin" | "security">;
  occurred_at: Generated<Timestamp>;
  on_behalf_of: string | null;
  payload: Generated<Json>;
  published_at: Timestamp | null;
  recorded_at: Generated<Timestamp>;
  schema_version: number;
  stream_id: string;
  stream_type: string;
}

export interface PlatformEventConsumption {
  consumed_at: Generated<Timestamp>;
  consumer: string;
  event_id: string;
}

export interface PlatformLookup {
  active: Generated<boolean>;
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  description: string | null;
  id: string;
  label: string;
  list_type: "department" | "job_role" | "document_category" | "sickness_type" | "ppe_type" | "leaver_reason" | "equipment_type";
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface PlatformNotification {
  action_url: string | null;
  body: string;
  channels: ('in_app' | 'email' | 'push')[];
  created_at: Generated<Timestamp>;
  created_by: string | null;
  dedupe_key: string | null;
  deleted_at: Timestamp | null;
  dispatched_at: Timestamp | null;
  expires_at: Timestamp | null;
  id: string;
  kind: string;
  /**
   * Template parameters, validated by the kind's registered Zod schema: ids and short non-sensitive display strings only. Special-category detail never appears here or in title/body on any channel (SA-023, ADR-0019).
   */
  payload: Generated<Json>;
  /**
   * Derived from the subject stream at send time, not configured — which is why it does not breach PL-021: no person is named in advance, only a relationship to the subject.
   */
  recipient_contextual: "subject_person" | "requester" | "subject_line_manager" | null;
  recipient_kind: "role" | "policy" | "contextual";
  recipient_policy_ref: string | null;
  recipient_role_id: string | null;
  recipient_team_id: string | null;
  status: Generated<"pending" | "dispatched" | "expired">;
  subject_stream_id: string | null;
  subject_stream_type: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface PlatformNotificationDelivery {
  attempt_count: Generated<number>;
  attempted_at: Timestamp | null;
  channel: "in_app" | "email" | "push";
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: string;
  last_error: string | null;
  notification_id: string;
  /**
   * The resolved recipient, stamped at send time. The only person reference in the notification model: a record of who was reached, never a configuration of who will be (PL-021).
   */
  person_id: string;
  provider_ref: string | null;
  read_at: Timestamp | null;
  resolved_via: "role" | "policy" | "contextual";
  status: Generated<"pending" | "sent" | "failed" | "dead" | "suppressed">;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface PlatformPerson {
  access_valid_until: Timestamp | null;
  agency_worker_reference: string | null;
  contact_email: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  date_of_birth: string | null;
  deleted_at: Timestamp | null;
  display_name: string;
  family_name: string | null;
  given_name: string | null;
  id: string;
  profile_status: Generated<"draft_shell" | "information_requested" | "information_submitted" | "pending_review" | "incomplete_rejected" | "approved_not_active" | "active" | "active_with_restrictions" | "inactive" | "leaver" | "reactivated">;
  relationship_type: "employee" | "agency" | "subcontractor" | "self_employed" | "external_org_employee" | "candidate";
  status: Generated<"active" | "inactive" | "superseded">;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface PlatformPersonAllocation {
  admin_person_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  end_reason: string | null;
  ended_at: Timestamp | null;
  ended_by: string | null;
  id: string;
  person_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  valid_from: Generated<Timestamp>;
  valid_until: Timestamp | null;
}

export interface PlatformPersonFlag {
  created_at: Generated<Timestamp>;
  end_reason: string | null;
  ended_at: Timestamp | null;
  ended_by: string | null;
  flag_type: "do_not_rehire" | "safeguarding" | "safety" | "other";
  id: string;
  person_id: string;
  raised_at: Timestamp;
  raised_by: string;
  reason: string;
  source_flag_id: string | null;
  source_merge_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PlatformPersonMerge {
  created_at: Generated<Timestamp>;
  id: string;
  merged_at: Timestamp;
  merged_by: string;
  moved_user_ids: Json;
  reason: string;
  reversal_reason: string | null;
  reversed_at: Timestamp | null;
  reversed_by: string | null;
  /**
   * platform.role_grant ids revoked by this merge (PL-042). Unmerge re-grants them as NEW rows — grants are never un-revoked (core plan 04 §4.3).
   */
  revoked_grant_ids: Json;
  superseded_person_id: string;
  surviving_person_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PlatformRole {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  description: string | null;
  id: string;
  is_system: Generated<boolean>;
  key: string;
  name: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface PlatformRoleGrant {
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  id: string;
  module: "platform" | "hr.core" | "hr.onboarding" | "hr.holiday_leave" | "hr.sickness_absence" | "hr.er" | "hr.ld" | "hr.offboarding" | "hr.wellbeing" | "hr.reporting";
  person_id: string;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  role_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  valid_from: Generated<Timestamp>;
  valid_until: Timestamp | null;
}

export interface PlatformScheduledAction {
  action_type: string;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  due_at: Timestamp;
  enqueued_at: Timestamp | null;
  executed_at: Timestamp | null;
  id: string;
  payload: Generated<Json>;
  source: "workflow" | "manual" | "system";
  status: Generated<"pending" | "enqueued" | "executed" | "cancelled">;
  subject_stream_id: string | null;
  subject_stream_type: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  workflow_instance_id: string | null;
}

export interface PlatformSignatureEvidence {
  ack_scrolled: boolean;
  created_at: Generated<Timestamp>;
  created_by: string;
  document_hash: string;
  document_id: string;
  id: string;
  ip: string;
  method: "typed_name" | "signature_pad";
  signatory_person_id: string;
  signature_image: Buffer | null;
  signed_at: Timestamp;
  typed_name: string | null;
  user_agent: string;
}

export interface PlatformTask {
  anchor_name: string | null;
  anchor_offset_days: number | null;
  assignee_role_id: string;
  cancel_reason: string | null;
  claimed_at: Timestamp | null;
  claimed_by: string | null;
  completed_at: Timestamp | null;
  completed_by: string | null;
  completion_note: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  description: string | null;
  due_at: Timestamp | null;
  due_mode: Generated<"none" | "absolute" | "anchor_relative">;
  id: string;
  lane: string | null;
  source: "workflow" | "manual";
  source_ref: string | null;
  status: Generated<"blocked" | "open" | "done" | "cancelled">;
  stream_id: string;
  stream_type: string;
  /**
   * Instructions, never personal or special-category data (ADR-0015/0019). The task links to its record; the record enforces field-level RBAC.
   */
  title: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  workflow_instance_id: string | null;
}

export interface PlatformTaskDependency {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  depends_on_kind: "task" | "gate";
  depends_on_task_id: string | null;
  gate_key: string | null;
  id: string;
  satisfied_at: Timestamp | null;
  task_id: string;
}

export interface PlatformTeam {
  /**
   * Optional hex colour for calendar rendering (plan 12 colour-by-team; core plan 05 §12.2 Q7). NULL means the consumer falls back to its own per-kind colours.
   */
  colour: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  deputy_person_id: string | null;
  description: string | null;
  id: string;
  manager_person_id: string;
  max_concurrent_leave: number | null;
  name: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface PlatformTeamMembership {
  created_at: Generated<Timestamp>;
  created_by: string;
  id: string;
  person_id: string;
  team_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  valid_from: string;
  valid_to: string | null;
}

export interface PlatformTemplate {
  archived_at: Timestamp | null;
  body_html: string;
  capture_schema_key: string | null;
  category_id: string;
  category_kind: Generated<"document_category">;
  created_at: Generated<Timestamp>;
  created_by: string;
  default_issue_mode: Generated<"read_only" | "read_and_sign" | "no_action" | "receipt_only" | "read_and_understood" | "qa_response" | "text_response" | "file_upload">;
  deleted_at: Timestamp | null;
  id: string;
  merge_contexts: Generated<string[]>;
  /**
   * Derived from body_html on save, never hand-entered: the declared field contract publish validates against, so a template cannot ship with an unsatisfiable token (§4.5).
   */
  merge_fields: Generated<Json>;
  name: string;
  published_at: Timestamp | null;
  status: Generated<"draft" | "published" | "archived">;
  template_key: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  version: number;
}

export interface PlatformWorkflowInstance {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  current_state: string;
  definition_version: number;
  deleted_at: Timestamp | null;
  id: string;
  subject_stream_id: string;
  subject_stream_type: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  workflow_key: string;
}

export interface PlatformWorkflowTransition {
  action: string;
  actor_person_id: string | null;
  comment: string | null;
  created_by: string | null;
  effects: Generated<Json>;
  from_state: string;
  guard_results: Generated<Json>;
  id: string;
  instance_id: string;
  occurred_at: Timestamp;
  on_behalf_of: string | null;
  recorded_at: Generated<Timestamp>;
  /**
   * The config: references this transition acted on, resolved as-at occurred_at (ADR-0016). Ids and primitive decision values only — never subject profile data (ADR-0019).
   */
  resolved_config: Generated<Json>;
  to_state: string;
}

export interface RateLimit {
  count: number;
  id: string;
  key: string;
  last_request: Int8;
}

export interface Session {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  impersonated_by: string | null;
  ip_address: string | null;
  token: string;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
  user_id: string;
}

export interface User {
  ban_expires: Timestamp | null;
  ban_reason: string | null;
  banned: Generated<boolean>;
  created_at: Generated<Timestamp>;
  email: string;
  email_verified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  person_id: string | null;
  role: Generated<"admin" | "agent">;
  updated_at: Generated<Timestamp>;
}

export interface Verification {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  identifier: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  "platform.approval_assignee": PlatformApprovalAssignee;
  "platform.approval_decision": PlatformApprovalDecision;
  "platform.approval_delegation": PlatformApprovalDelegation;
  "platform.approval_request": PlatformApprovalRequest;
  "platform.config_entry": PlatformConfigEntry;
  "platform.document": PlatformDocument;
  "platform.domain_event": PlatformDomainEvent;
  "platform.event_consumption": PlatformEventConsumption;
  "platform.lookup": PlatformLookup;
  "platform.notification": PlatformNotification;
  "platform.notification_delivery": PlatformNotificationDelivery;
  "platform.person": PlatformPerson;
  "platform.person_allocation": PlatformPersonAllocation;
  "platform.person_flag": PlatformPersonFlag;
  "platform.person_merge": PlatformPersonMerge;
  "platform.role": PlatformRole;
  "platform.role_grant": PlatformRoleGrant;
  "platform.scheduled_action": PlatformScheduledAction;
  "platform.signature_evidence": PlatformSignatureEvidence;
  "platform.task": PlatformTask;
  "platform.task_dependency": PlatformTaskDependency;
  "platform.team": PlatformTeam;
  "platform.team_membership": PlatformTeamMembership;
  "platform.template": PlatformTemplate;
  "platform.workflow_instance": PlatformWorkflowInstance;
  "platform.workflow_transition": PlatformWorkflowTransition;
  rate_limit: RateLimit;
  session: Session;
  user: User;
  verification: Verification;
}
