/**
 * This file is GENERATED by kysely-codegen (`pnpm migrate:generate`).
 * DO NOT EDIT BY HAND — re-run codegen against the migrated database instead.
 *
 * The initial version below reflects the `auth-tables` migration (Better Auth
 * base tables + admin plugin columns). The `user.role` literal union comes from
 * the CHECK constraint via `.kysely-codegenrc.json` overrides.
 */
import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  id: string;
  account_id: string;
  provider_id: string;
  user_id: string;
  access_token: string | null;
  refresh_token: string | null;
  id_token: string | null;
  access_token_expires_at: Timestamp | null;
  refresh_token_expires_at: Timestamp | null;
  scope: string | null;
  password: string | null;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface Session {
  id: string;
  expires_at: Timestamp;
  token: string;
  ip_address: string | null;
  user_agent: string | null;
  user_id: string;
  impersonated_by: string | null;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface User {
  id: string;
  name: string;
  email: string;
  email_verified: Generated<boolean>;
  image: string | null;
  role: Generated<'admin' | 'agent'>;
  banned: Generated<boolean>;
  ban_reason: string | null;
  ban_expires: Timestamp | null;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface Verification {
  id: string;
  identifier: string;
  value: string;
  expires_at: Timestamp;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  account: Account;
  session: Session;
  user: User;
  verification: Verification;
}
