/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard';
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin';
import { Route as AuthenticatedAdminTeamsIndexRouteImport } from './routes/_authenticated/admin/teams/index';
import { Route as AuthenticatedAdminReferenceDataIndexRouteImport } from './routes/_authenticated/admin/reference-data/index';
import { Route as AuthenticatedAdminPeopleIndexRouteImport } from './routes/_authenticated/admin/people/index';
import { Route as AuthenticatedAdminTeamsTeamIdRouteImport } from './routes/_authenticated/admin/teams/$teamId';
import { Route as AuthenticatedAdminReferenceDataListTypeRouteImport } from './routes/_authenticated/admin/reference-data/$listType';
import { Route as AuthenticatedAdminPeopleNewRouteImport } from './routes/_authenticated/admin/people/new';
import { Route as AuthenticatedAdminPeopleDuplicatesRouteImport } from './routes/_authenticated/admin/people/duplicates';
import { Route as AuthenticatedAdminPeoplePersonIdRouteImport } from './routes/_authenticated/admin/people/$personId';
import { Route as AuthenticatedAdminAuthzRolesRouteImport } from './routes/_authenticated/admin/authz/roles';
import { Route as AuthenticatedAdminAuthzGrantsRouteImport } from './routes/_authenticated/admin/authz/grants';
import { Route as AuthenticatedAdminAuthzAllocationsRouteImport } from './routes/_authenticated/admin/authz/allocations';

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAdminTeamsIndexRoute =
  AuthenticatedAdminTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminReferenceDataIndexRoute =
  AuthenticatedAdminReferenceDataIndexRouteImport.update({
    id: '/reference-data/',
    path: '/reference-data/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminPeopleIndexRoute =
  AuthenticatedAdminPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminTeamsTeamIdRoute =
  AuthenticatedAdminTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminReferenceDataListTypeRoute =
  AuthenticatedAdminReferenceDataListTypeRouteImport.update({
    id: '/reference-data/$listType',
    path: '/reference-data/$listType',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminPeopleNewRoute =
  AuthenticatedAdminPeopleNewRouteImport.update({
    id: '/people/new',
    path: '/people/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminPeopleDuplicatesRoute =
  AuthenticatedAdminPeopleDuplicatesRouteImport.update({
    id: '/people/duplicates',
    path: '/people/duplicates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminPeoplePersonIdRoute =
  AuthenticatedAdminPeoplePersonIdRouteImport.update({
    id: '/people/$personId',
    path: '/people/$personId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminAuthzRolesRoute =
  AuthenticatedAdminAuthzRolesRouteImport.update({
    id: '/authz/roles',
    path: '/authz/roles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminAuthzGrantsRoute =
  AuthenticatedAdminAuthzGrantsRouteImport.update({
    id: '/authz/grants',
    path: '/authz/grants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminAuthzAllocationsRoute =
  AuthenticatedAdminAuthzAllocationsRouteImport.update({
    id: '/authz/allocations',
    path: '/authz/allocations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/admin': typeof AuthenticatedAdminRouteWithChildren;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/admin/authz/allocations': typeof AuthenticatedAdminAuthzAllocationsRoute;
  '/admin/authz/grants': typeof AuthenticatedAdminAuthzGrantsRoute;
  '/admin/authz/roles': typeof AuthenticatedAdminAuthzRolesRoute;
  '/admin/people/$personId': typeof AuthenticatedAdminPeoplePersonIdRoute;
  '/admin/people/duplicates': typeof AuthenticatedAdminPeopleDuplicatesRoute;
  '/admin/people/new': typeof AuthenticatedAdminPeopleNewRoute;
  '/admin/reference-data/$listType': typeof AuthenticatedAdminReferenceDataListTypeRoute;
  '/admin/teams/$teamId': typeof AuthenticatedAdminTeamsTeamIdRoute;
  '/admin/people/': typeof AuthenticatedAdminPeopleIndexRoute;
  '/admin/reference-data/': typeof AuthenticatedAdminReferenceDataIndexRoute;
  '/admin/teams/': typeof AuthenticatedAdminTeamsIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/admin': typeof AuthenticatedAdminRouteWithChildren;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/admin/authz/allocations': typeof AuthenticatedAdminAuthzAllocationsRoute;
  '/admin/authz/grants': typeof AuthenticatedAdminAuthzGrantsRoute;
  '/admin/authz/roles': typeof AuthenticatedAdminAuthzRolesRoute;
  '/admin/people/$personId': typeof AuthenticatedAdminPeoplePersonIdRoute;
  '/admin/people/duplicates': typeof AuthenticatedAdminPeopleDuplicatesRoute;
  '/admin/people/new': typeof AuthenticatedAdminPeopleNewRoute;
  '/admin/reference-data/$listType': typeof AuthenticatedAdminReferenceDataListTypeRoute;
  '/admin/teams/$teamId': typeof AuthenticatedAdminTeamsTeamIdRoute;
  '/admin/people': typeof AuthenticatedAdminPeopleIndexRoute;
  '/admin/reference-data': typeof AuthenticatedAdminReferenceDataIndexRoute;
  '/admin/teams': typeof AuthenticatedAdminTeamsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/login': typeof LoginRoute;
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren;
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute;
  '/_authenticated/admin/authz/allocations': typeof AuthenticatedAdminAuthzAllocationsRoute;
  '/_authenticated/admin/authz/grants': typeof AuthenticatedAdminAuthzGrantsRoute;
  '/_authenticated/admin/authz/roles': typeof AuthenticatedAdminAuthzRolesRoute;
  '/_authenticated/admin/people/$personId': typeof AuthenticatedAdminPeoplePersonIdRoute;
  '/_authenticated/admin/people/duplicates': typeof AuthenticatedAdminPeopleDuplicatesRoute;
  '/_authenticated/admin/people/new': typeof AuthenticatedAdminPeopleNewRoute;
  '/_authenticated/admin/reference-data/$listType': typeof AuthenticatedAdminReferenceDataListTypeRoute;
  '/_authenticated/admin/teams/$teamId': typeof AuthenticatedAdminTeamsTeamIdRoute;
  '/_authenticated/admin/people/': typeof AuthenticatedAdminPeopleIndexRoute;
  '/_authenticated/admin/reference-data/': typeof AuthenticatedAdminReferenceDataIndexRoute;
  '/_authenticated/admin/teams/': typeof AuthenticatedAdminTeamsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/admin/authz/allocations'
    | '/admin/authz/grants'
    | '/admin/authz/roles'
    | '/admin/people/$personId'
    | '/admin/people/duplicates'
    | '/admin/people/new'
    | '/admin/reference-data/$listType'
    | '/admin/teams/$teamId'
    | '/admin/people/'
    | '/admin/reference-data/'
    | '/admin/teams/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/admin/authz/allocations'
    | '/admin/authz/grants'
    | '/admin/authz/roles'
    | '/admin/people/$personId'
    | '/admin/people/duplicates'
    | '/admin/people/new'
    | '/admin/reference-data/$listType'
    | '/admin/teams/$teamId'
    | '/admin/people'
    | '/admin/reference-data'
    | '/admin/teams';
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/authz/allocations'
    | '/_authenticated/admin/authz/grants'
    | '/_authenticated/admin/authz/roles'
    | '/_authenticated/admin/people/$personId'
    | '/_authenticated/admin/people/duplicates'
    | '/_authenticated/admin/people/new'
    | '/_authenticated/admin/reference-data/$listType'
    | '/_authenticated/admin/teams/$teamId'
    | '/_authenticated/admin/people/'
    | '/_authenticated/admin/reference-data/'
    | '/_authenticated/admin/teams/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin': {
      id: '/_authenticated/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AuthenticatedAdminRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/teams/': {
      id: '/_authenticated/admin/teams/';
      path: '/teams';
      fullPath: '/admin/teams/';
      preLoaderRoute: typeof AuthenticatedAdminTeamsIndexRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/reference-data/': {
      id: '/_authenticated/admin/reference-data/';
      path: '/reference-data';
      fullPath: '/admin/reference-data/';
      preLoaderRoute: typeof AuthenticatedAdminReferenceDataIndexRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/people/': {
      id: '/_authenticated/admin/people/';
      path: '/people';
      fullPath: '/admin/people/';
      preLoaderRoute: typeof AuthenticatedAdminPeopleIndexRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/teams/$teamId': {
      id: '/_authenticated/admin/teams/$teamId';
      path: '/teams/$teamId';
      fullPath: '/admin/teams/$teamId';
      preLoaderRoute: typeof AuthenticatedAdminTeamsTeamIdRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/reference-data/$listType': {
      id: '/_authenticated/admin/reference-data/$listType';
      path: '/reference-data/$listType';
      fullPath: '/admin/reference-data/$listType';
      preLoaderRoute: typeof AuthenticatedAdminReferenceDataListTypeRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/people/new': {
      id: '/_authenticated/admin/people/new';
      path: '/people/new';
      fullPath: '/admin/people/new';
      preLoaderRoute: typeof AuthenticatedAdminPeopleNewRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/people/duplicates': {
      id: '/_authenticated/admin/people/duplicates';
      path: '/people/duplicates';
      fullPath: '/admin/people/duplicates';
      preLoaderRoute: typeof AuthenticatedAdminPeopleDuplicatesRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/people/$personId': {
      id: '/_authenticated/admin/people/$personId';
      path: '/people/$personId';
      fullPath: '/admin/people/$personId';
      preLoaderRoute: typeof AuthenticatedAdminPeoplePersonIdRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/authz/roles': {
      id: '/_authenticated/admin/authz/roles';
      path: '/authz/roles';
      fullPath: '/admin/authz/roles';
      preLoaderRoute: typeof AuthenticatedAdminAuthzRolesRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/authz/grants': {
      id: '/_authenticated/admin/authz/grants';
      path: '/authz/grants';
      fullPath: '/admin/authz/grants';
      preLoaderRoute: typeof AuthenticatedAdminAuthzGrantsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    '/_authenticated/admin/authz/allocations': {
      id: '/_authenticated/admin/authz/allocations';
      path: '/authz/allocations';
      fullPath: '/admin/authz/allocations';
      preLoaderRoute: typeof AuthenticatedAdminAuthzAllocationsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuthzAllocationsRoute: typeof AuthenticatedAdminAuthzAllocationsRoute;
  AuthenticatedAdminAuthzGrantsRoute: typeof AuthenticatedAdminAuthzGrantsRoute;
  AuthenticatedAdminAuthzRolesRoute: typeof AuthenticatedAdminAuthzRolesRoute;
  AuthenticatedAdminPeoplePersonIdRoute: typeof AuthenticatedAdminPeoplePersonIdRoute;
  AuthenticatedAdminPeopleDuplicatesRoute: typeof AuthenticatedAdminPeopleDuplicatesRoute;
  AuthenticatedAdminPeopleNewRoute: typeof AuthenticatedAdminPeopleNewRoute;
  AuthenticatedAdminReferenceDataListTypeRoute: typeof AuthenticatedAdminReferenceDataListTypeRoute;
  AuthenticatedAdminTeamsTeamIdRoute: typeof AuthenticatedAdminTeamsTeamIdRoute;
  AuthenticatedAdminPeopleIndexRoute: typeof AuthenticatedAdminPeopleIndexRoute;
  AuthenticatedAdminReferenceDataIndexRoute: typeof AuthenticatedAdminReferenceDataIndexRoute;
  AuthenticatedAdminTeamsIndexRoute: typeof AuthenticatedAdminTeamsIndexRoute;
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuthzAllocationsRoute:
    AuthenticatedAdminAuthzAllocationsRoute,
  AuthenticatedAdminAuthzGrantsRoute: AuthenticatedAdminAuthzGrantsRoute,
  AuthenticatedAdminAuthzRolesRoute: AuthenticatedAdminAuthzRolesRoute,
  AuthenticatedAdminPeoplePersonIdRoute: AuthenticatedAdminPeoplePersonIdRoute,
  AuthenticatedAdminPeopleDuplicatesRoute:
    AuthenticatedAdminPeopleDuplicatesRoute,
  AuthenticatedAdminPeopleNewRoute: AuthenticatedAdminPeopleNewRoute,
  AuthenticatedAdminReferenceDataListTypeRoute:
    AuthenticatedAdminReferenceDataListTypeRoute,
  AuthenticatedAdminTeamsTeamIdRoute: AuthenticatedAdminTeamsTeamIdRoute,
  AuthenticatedAdminPeopleIndexRoute: AuthenticatedAdminPeopleIndexRoute,
  AuthenticatedAdminReferenceDataIndexRoute:
    AuthenticatedAdminReferenceDataIndexRoute,
  AuthenticatedAdminTeamsIndexRoute: AuthenticatedAdminTeamsIndexRoute,
};

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren);

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren;
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
